### PR TITLE
Incrementing supported Monodevelop version to support VS for Mac

### PR DESCRIPTION
**Pull request by jimbobbennett**
Also deleting packages from github repo

### CODE REVIEW

**Comment by jimbobbennett** [comment]
This isn't perfect at the moment - syntax colouring doesn't work as the APIs are different, but the extension builds and can be installed.

**Comment by jimbobbennett** [comment]
@mikeyjones - this will remove XS support, so don't know if you'd rather create a new branch and I'll point the PR to that.

**Comment by mikeyjones** [comment]
Hi Jim,

I am so sorry for not acknowledging this sooner. I've just been so busy with work and family, I haven't looked at GitHub for a bit. I changed jobs too, and didn't change my email address on GitHub, so wasn't getting emails, that's fixed now!

I think we need make a new branch for this, so we can keep backwards compatibility with XS. So I'll look at doing that (probably this weekend). The other thing I wanted to do was to remove the need to compile SpecFlow libraries for source and use Nuget instead. I think this project and the core SpecFlow project have moved apart enough that we can separate this into it's own entity.

would you be up for co-administration this with me?

Mike

**Comment by jimbobbennett** [comment]
Hey no worries - I know how life goes :)

I'd love to help out - I use spec flow a lot so would be good for there to be a working extension in VS for Mac. Not sure how much time I’ll have but I’ll do what I can!

Jim

**Comment by jimbobbennett** [comment]
@mikeyjones - new branch created and PR raised for the new branch

**Comment by jimbobbennett** [comment]
@mikeyjones - I'm working on this now, sorry for taking so long. Got it all working using the SpecFlow nugets, all the code that is left is the IdeIntegration and main project. Just stuck on syntax highlighting, so trying to get that done. I've reached out to Mikayla at Xamarin for help so see where I get with it. Will raise a big PR with the changes soon.

**Pull request closed without merging**
