### PR TITLE
Almost working VS for Mac port

### PR DESCRIPTION
**Pull request by jimbobbennett**
This is a port to VS for Mac, including removing all the spec flow code and replacing with NuGet packages.

At the moment it pretty much works, but syntax highlighting isn't working. I'm working on this but wanted to get an initial PR in for review.

### CODE REVIEW

**Comment by mikeyjones** [comment]
Hi Jim it's early morning here, I'll test this tonight, and then merge if it's all good. I love the amount of deletions, this has got to make it easier for us to maintain.

Thanks for all your support on this. I wouldn't have had to the time to react so quickly.

Are you looking into the sites highlighting? I'm happy to do it, just don't want to duplicate effort.

**Comment by jimbobbennett** [comment]
I'm looking at the syntax highlighting at the moment, hope to get it done tomorrow morning my time. Mikayla has been helping me with it and I think I know what to do. Will keep you updated!

**Comment by mikeyjones** [comment]
Thanks mate. I'll leave that to you then.

**Comment by jimbobbennett** [comment]
Syntax highlighting now works. I've given the extension a quick test and it looks ok to me. I haven't tested the syntax highlighting with the dark theme, and I haven't done a detailed test - just checked the file creation and updates when editing feature files. Will do more testing tomorrow unless you want to give it a thorough go over.

**Comment by mikeyjones** [comment]
I've been testing it and am happy with it so merged the pull request.  Tested the syntax highlighting  on both light and dark. I will get an mpack ready for release and then look at how we get it in the extensions.

Thanks for all your work on this. I don't think I would have, found how to do the syntax highlighting. Mikayla's a great help

**Comment by jimbobbennett** [comment]
It's pretty easy to get it into the extensions gallery - just point it at the source and away you go . Before we do I wanted to discuss naming. Is it ok to call it specflow or do tech talk have a copyright on that?

**Comment by mikeyjones** [comment]
I spoke to them about it a while ago, and they didn't have a problem with us using Spec Flow. We could remove the Tech Talk part of it and make it clear that this is unoffical, and try and avoid copyright issues. Do you have any names in mind?

They didn't care when it was Xamarin Studio, but now it has the weight of MS behind it, they might take more offence

**Comment by mikeyjones** [comment]
What about if we call it "straight8 SpecFlow intergration" straight8 is a type of cucumber, and I thought it sounded a bit different, I could register the org "strighteight" on github, and make you a co owner, that way you can have the credit you deserve for the work you are doing! 

I think as long as we make it clear that it is not official, and is a tool to allow people to use SpecFlow in VSMac, it should be OK. It's not like we are trying to monetize it.

**Comment by jimbobbennett** [comment]
Sounds good to me! If you want to create an org and transfer the repo to it (I guess also break the link to the original tech talk repo) or transfer the code I can set up the extension in the Monodevelop add-ins repo.

🥒

**Pull request merged**
